'use client';

import CharacterHtmlIntro from "@/components/CharacterHtmlIntro";

type PreviewCharacter = { name: string; description?: string; avatar?: string | null; cover?: string; tags?: string[]; opening?: string; story?: string; authorHtml?: string };

export default function CharacterPreviewModal({ character, onClose }: { character: PreviewCharacter; onClose: () => void }) {
  const background = character.cover || character.avatar || "";
  return <div className="fixed inset-0 z-[70] overflow-y-auto bg-[#050508]/90 p-3 backdrop-blur-xl sm:p-8" role="dialog" aria-modal="true" aria-label="角色预览"><div className="mx-auto max-w-5xl"><div className="mb-4 flex items-center justify-between text-white"><div><p className="text-[10px] tracking-[.35em] text-[#c7a7ff]">LIVE PREVIEW</p><h2 className="mt-1 text-xl font-black">角色详情与聊天效果</h2></div><button onClick={onClose} className="rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm hover:bg-white/20">关闭预览</button></div><div className="overflow-hidden rounded-[28px] border border-white/15 bg-[#0c0b13] shadow-2xl"><div className="h-48 bg-cover bg-center" style={{ backgroundImage: background ? `linear-gradient(#05050866,#0c0b13),url("${background}")` : undefined }} /><div className="-mt-16 px-5 pb-7 sm:px-8"><div className="flex items-end gap-4"><img src={character.avatar || "/placeholder.png"} alt="" className="h-28 w-28 rounded-2xl border-4 border-[#0c0b13] object-cover" /><div className="pb-1"><h1 className="text-3xl font-black text-white">{character.name || "未命名角色"}</h1><p className="mt-1 text-sm text-white/60">{character.description || "角色简介会显示在这里。"}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{character.tags?.map((tag) => <span key={tag} className="rounded-full bg-[#786BD4]/25 px-3 py-1 text-xs text-[#ddd7ff]">#{tag}</span>)}</div>{character.authorHtml && <CharacterHtmlIntro content={character.authorHtml} title="小剧场预览" className="mt-6 h-[360px]" />}{character.story && <p className="mt-6 whitespace-pre-wrap text-sm leading-7 text-white/65">{character.story}</p>}</div></div><section className="mt-5 overflow-hidden rounded-[28px] border border-white/15 bg-[#11101a]"><header className="flex items-center gap-3 border-b border-white/10 bg-white/[.08] p-4"><img src={character.avatar || "/placeholder.png"} alt="" className="h-10 w-10 rounded-full object-cover" /><div><b className="text-white">{character.name || "未命名角色"}</b><p className="text-xs text-white/45">聊天预览</p></div></header><div className="min-h-64 bg-cover bg-center p-5" style={{ backgroundImage: background ? `linear-gradient(rgba(5,6,12,.72),rgba(5,6,12,.82)),url("${background}")` : undefined }}><div className="max-w-xl rounded-2xl border border-white/60 bg-white/[.82] p-4 text-sm leading-7 text-[#202635]">{character.opening || "开场白会在正式聊天开始前显示在这里。"}</div><div className="ml-auto mt-4 max-w-xs rounded-2xl border border-white/70 bg-[#e8f2ff]/85 p-4 text-sm text-[#202635]">你好。</div><div className="mt-4 max-w-xs rounded-2xl border border-white/60 bg-white/[.82] p-4 text-sm text-[#202635]">角色的第一句回复会以这样的形式呈现。</div></div></section></div></div>;
}
